-- ============================================================
-- Smart City Traffic Management System - Database Schema
-- MySQL 8.0+
-- ============================================================

CREATE DATABASE IF NOT EXISTS smart_traffic_db
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE smart_traffic_db;

-- ------------------------------------------------------------
-- 1. Users  (Admin / Traffic Officer accounts)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS Users (
    user_id       INT AUTO_INCREMENT PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    email         VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          ENUM('admin', 'officer') NOT NULL DEFAULT 'officer',
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- 2. Roads
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS Roads (
    road_id     INT AUTO_INCREMENT PRIMARY KEY,
    road_name   VARCHAR(150) NOT NULL UNIQUE,
    location    VARCHAR(150),
    latitude    DECIMAL(9,6),
    longitude   DECIMAL(9,6),
    road_type   ENUM('highway', 'arterial', 'residential', 'collector') DEFAULT 'arterial',
    signal_id   VARCHAR(50),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- 3. TrafficData
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS TrafficData (
    traffic_id        INT AUTO_INCREMENT PRIMARY KEY,
    road_id            INT NOT NULL,
    vehicle_count      INT NOT NULL,
    avg_speed          FLOAT NOT NULL,
    weather            VARCHAR(50) DEFAULT 'clear',
    record_date        DATE NOT NULL,
    record_time        TIME NOT NULL,
    day_of_week        VARCHAR(15),
    congestion_level   ENUM('low', 'medium', 'high') DEFAULT NULL,  -- actual/labelled level (nullable for new/unlabelled records)
    created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (road_id) REFERENCES Roads(road_id) ON DELETE CASCADE,
    INDEX idx_traffic_road_date (road_id, record_date)
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- 4. Predictions
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS Predictions (
    prediction_id   INT AUTO_INCREMENT PRIMARY KEY,
    traffic_id      INT NOT NULL,
    model_used      ENUM('random_forest', 'lstm') NOT NULL,
    predicted_level VARCHAR(20),          -- low/medium/high (Random Forest)
    predicted_speed FLOAT,                -- forecasted speed (LSTM, nullable)
    confidence      FLOAT,                -- model confidence / probability
    predicted_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (traffic_id) REFERENCES TrafficData(traffic_id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- 5. Incidents
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS Incidents (
    incident_id    INT AUTO_INCREMENT PRIMARY KEY,
    road_id        INT,
    raw_text       TEXT NOT NULL,
    incident_type  VARCHAR(50),    -- extracted by NLP (accident, flooding, roadwork, etc.)
    severity       VARCHAR(20),    -- extracted by NLP (low/medium/high/critical)
    weather        VARCHAR(50),    -- extracted by NLP
    reported_by    VARCHAR(100),
    reported_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (road_id) REFERENCES Roads(road_id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- 6. Alerts
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS Alerts (
    alert_id      INT AUTO_INCREMENT PRIMARY KEY,
    incident_id   INT,
    road_id       INT,
    alert_text    TEXT NOT NULL,     -- generated by FLAN-T5 Small
    generated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (incident_id) REFERENCES Incidents(incident_id) ON DELETE SET NULL,
    FOREIGN KEY (road_id) REFERENCES Roads(road_id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- 7. AgentLogs
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS AgentLogs (
    log_id         INT AUTO_INCREMENT PRIMARY KEY,
    road_id        INT,
    prediction_id  INT,
    incident_id    INT,
    decision       VARCHAR(255) NOT NULL,   -- e.g. "Extend green signal by 15s"
    reason         VARCHAR(255),            -- why the agent decided this
    urgency        ENUM('low','medium','high','critical') DEFAULT 'low',
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (road_id) REFERENCES Roads(road_id) ON DELETE SET NULL,
    FOREIGN KEY (prediction_id) REFERENCES Predictions(prediction_id) ON DELETE SET NULL,
    FOREIGN KEY (incident_id) REFERENCES Incidents(incident_id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- 8. Reports
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS Reports (
    report_id     INT AUTO_INCREMENT PRIMARY KEY,
    report_type   ENUM('daily', 'weekly', 'monthly') NOT NULL,
    start_date    DATE NOT NULL,
    end_date      DATE NOT NULL,
    file_path     VARCHAR(255),
    generated_by  INT,
    generated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (generated_by) REFERENCES Users(user_id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- Seed data: default admin user (password: Admin@123, hashed at app startup)
-- and a starter set of roads matching the sample dataset.
-- ------------------------------------------------------------
INSERT INTO Roads (road_name, location, latitude, longitude, road_type, signal_id) VALUES
('MG Road', 'Chennai Central', 13.0827, 80.2707, 'arterial', 'SIG-001'),
('Anna Salai', 'Chennai', 13.0604, 80.2496, 'arterial', 'SIG-002'),
('OMR', 'Chennai IT Corridor', 12.8956, 80.2270, 'highway', 'SIG-003'),
('ECR', 'Chennai East Coast', 12.8406, 80.2336, 'highway', 'SIG-004'),
('GST Road', 'Chennai South', 12.9908, 80.1690, 'arterial', 'SIG-005'),
('Mount Road', 'Chennai', 13.0569, 80.2425, 'arterial', 'SIG-006'),
('Poonamallee High Road', 'Chennai West', 13.0732, 80.2197, 'collector', 'SIG-007'),
('Velachery Main Road', 'Chennai South', 12.9756, 80.2207, 'collector', 'SIG-008'),
('Sardar Patel Road', 'Chennai', 13.0108, 80.2350, 'arterial', 'SIG-009'),
('Rajiv Gandhi Salai', 'Chennai IT Corridor', 12.8406, 80.1530, 'highway', 'SIG-010');
